In [4]:
from sbw import *

In [5]:
import numpy as np
# 创建一个标量, 0维张量
x=np.array(12)
print(x,x.ndim,x.shape)
# 创建一个1维张量
y=np.array([11,12])
print(y,y.ndim,y.shape)

12 0 ()
[11 12] 1 (2,)


In [6]:
import time

# 测试张量运算的速度
x=np.random.random((20,100))
y=np.random.random((20,100))
t0=time.time()
for i in range(10000):
    z=x+y
    z=np.maximum(z,0.)
print(f'Took:{time.time()-t0:.2f}')

Took:0.02


In [7]:
# 创建一个一维张量
x=np.random.random((10,))
# 指定的轴, 意味如何扩展
# axis=0, 新建一个轴
# axis>0, 将相应层次的元素, 包裹在新的容器中
y=np.expand_dims(x,0)
print(y.shape)
z=np.concatenate([x]*32,0)
print(z.shape)

(1, 10)
(320,)


In [8]:
x=np.random.random((2,3))
print(x)
print_line()
# 扩展最外层容器
y=np.expand_dims(x,0)
print(y)
print_line()

# 扩展次级容器
z=np.expand_dims(x,1)
print(z)
print_line()

# 扩展单个元素为容器
w=np.expand_dims(x,2)
print(w)

[[0.97816813 0.32605524 0.16020166]
 [0.91787138 0.59435978 0.14186197]]
[[[0.97816813 0.32605524 0.16020166]
  [0.91787138 0.59435978 0.14186197]]]
[[[0.97816813 0.32605524 0.16020166]]

 [[0.91787138 0.59435978 0.14186197]]]
[[[0.97816813]
  [0.32605524]
  [0.16020166]]

 [[0.91787138]
  [0.59435978]
  [0.14186197]]]


In [ ]:
# 不同维度张量之间的计算
# 自动复用低维张量
x=np.random.random((2,3,4))
print(x)
print_line()

y=np.random.random((3,4))
print(y)
print_line()

z=np.maximum(x,y)
print(z)
print_line()

[[[0.65812368 0.22743063 0.72175884 0.20133926]
  [0.19485901 0.82429744 0.20756484 0.90399007]
  [0.54525334 0.02986789 0.30395999 0.37522271]]

 [[0.82885    0.88139496 0.02693518 0.91195409]
  [0.66489059 0.88658831 0.5771144  0.08818289]
  [0.26890112 0.09318265 0.4196997  0.55682072]]]
[[0.87632723 0.89319443 0.77917156 0.44523289]
 [0.95014087 0.40467806 0.03742003 0.35172256]
 [0.02539775 0.98992056 0.68435239 0.95690479]]
[[[0.87632723 0.89319443 0.77917156 0.44523289]
  [0.95014087 0.82429744 0.20756484 0.90399007]
  [0.54525334 0.98992056 0.68435239 0.95690479]]

 [[0.87632723 0.89319443 0.77917156 0.91195409]
  [0.95014087 0.88658831 0.5771144  0.35172256]
  [0.26890112 0.98992056 0.68435239 0.95690479]]]


In [ ]:
# 模拟实现张量运算

from numpy import ndarray
def native_vector_dot(v1:list,v2:list):
    assert len(v1)==len(v2)
    return sum(n1*n2 for n1,n2 in zip(v1,v2))

def native_matrix_dot(mat1:ndarray,mat2:ndarray):
    assert np.shape(mat1)[1]==np.shape(mat2)[0]
    r=np.shape(mat1)[0]
    c=np.shape(mat2)[1]
    ret=np.zeros((r,c))
    for r in range(np.shape(mat1)[0]):
        for c in range(np.shape(mat2)[1]):
            ret[r][c]=native_vector_dot(mat1[r,:],mat2[:,c])
    return ret


In [ ]:
x=np.random.random((2,3))
y=np.random.random((3,2))
z1=np.dot(x,y)
print(z1)
print_line()
z2=native_matrix_dot(x,y)
print(z2)
print_line()


[[0.95150973 0.94042511]
 [0.83633959 0.74816255]]
[[0.95150973 0.94042511]
 [0.83633959 0.74816255]]
