In [5]:
# 创建张量常数矩阵
# tensorflow创建的矩阵不可变
import tensorflow as tf

ones=tf.ones(shape=(2,1))
print(ones)
zeros=tf.zeros(shape=(1,2))
print(zeros)

# 正态分布, 钟形曲线
normals=tf.random.normal(shape=(3,1),mean=0,stddev=1)
print(normals)
# 均匀分布, 矩形
uniforms=tf.random.uniform(shape=(1,3),minval=0,maxval=1)
print(uniforms)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[ 0.02721338]
 [ 0.68467593]
 [-0.26875126]], shape=(3, 1), dtype=float32)
tf.Tensor([[0.39904344 0.87837374 0.99560297]], shape=(1, 3), dtype=float32)


In [10]:
# 创建张量变量矩阵

v=tf.Variable(normals)
print(v)

# 为变量赋值
# 赋值操作必须通过assign
# 批量赋值
v.assign(tf.ones((3,1)))
print(v)
# 单个元素赋值
v[1,0].assign(2.)
print(v)
# 加法赋值
v.assign_add(tf.ones((3,1)))
print(v)
# 减法赋值
v.assign_sub(tf.random.uniform((3,1),maxval=3))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.02721338],
       [ 0.68467593],
       [-0.26875126]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [2.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[2.],
       [3.],
       [2.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.143331 ],
       [2.611687 ],
       [1.1301035]], dtype=float32)>


In [23]:
# 张量的运算


x=tf.random.uniform((2,2))
print(x)

xx=tf.square(x)
print(xx)

xx=tf.sqrt(x)
print(xx)

xx=x+x
print(xx)

xx=x*x
print(xx)

x/=x
print(x)

tf.Tensor(
[[0.28504586 0.7987139 ]
 [0.31637204 0.6783092 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.08125114 0.6379439 ]
 [0.10009126 0.46010336]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.53389686 0.893708  ]
 [0.5624696  0.8235953 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.5700917 1.5974278]
 [0.6327441 1.3566184]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.08125114 0.6379439 ]
 [0.10009126 0.46010336]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [36]:
# GradientTape 梯度计算

v=tf.Variable(3.)
with tf.GradientTape() as tape:
    result=v*v+4*v
gradient=tape.gradient(result,v)
print(gradient)

# 计算任意输入的梯度
n=tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(n)
    result=n**3+4*n
gradient=tape.gradient(result,n)
print(gradient)

# 嵌套梯度计算, 计算梯度的梯度
time=tf.Variable(3.)
with tf.GradientTape() as speed_tape:
    with tf.GradientTape() as position_tape:
        position=0.5*9.8*time**2 # 物体自由落体
    speed=position_tape.gradient(position,time)
    print('speed',speed)
acceleration=speed_tape.gradient(speed,time)
print('acceleration',acceleration)

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor(31.0, shape=(), dtype=float32)
speed tf.Tensor(29.400002, shape=(), dtype=float32)
acceleration tf.Tensor(9.8, shape=(), dtype=float32)
